### ISSUE TITLE
Why is this plugin not popular?

### ISSUE THREAD

**Issue by garygreen** [xymak/php-smartcrop-extension#1]
Seems pretty useful, no? Is it complete and ready to be used in production? 😄

**Comment by xymak** [comment]
No, Using gd to analyse image in php extension is not efficient. Opencv is a better choice. I'm developing a opencv version of this extension which is expected to used in a real time online image service.

**Comment by garygreen** [comment]
Nice. It did seem a bit slow when testing (the php script version, haven't tried this extension) although it did have quite a few differences between the smartcrop.js version and what this version outputs - maybe it's some changes in smartcrop but from a few images I was testing with it cropped off people's heads but smartcrop.js didnt, even without the face detection enabled.

**Comment by xymak** [comment]
In php script, image matrix could not be exported to a php array. Calling a php function in a for loop to obtain color value of a pixel is  so inefficiency that php scipt version is very slow.
In php js version, image matrix could be exported to a array by canvas. It is more effieciency than php version to obtain color value of a pixel.
In different image processing library (php-gd/php-imgick/js-canvas), a rgb color value of a pixel is different.This difference cause difference between php script version output and js script version output.  It did have differences between gd branch output and imagick branch out in this version output.
