### ISSUE TITLE
 https-p2guides-wordpress-com

### ISSUE THREAD

**Issue by antoniosuperba** [xymak/php-smartcrop-extension#3]
![IMG_hs4vhs](https://user-images.githubusercontent.com/77815546/106278867-bc7f8b80-623b-11eb-80f5-410b6f28ea4a.jpg)
****[ ****Antonio Antonio spurs]( https://support.google.com/chrome/answer/95759?hl=hr)

**Comment by jday8800** [comment]
@*@#All#done#here-caught

**Comment by jday8800** [comment]
> @*@#All#done#here-caught

💎💫💎🍀
